export const mainCarouselData = [
    {
        image: 'https://rukminim1.flixcart.com/image/612/612/kw5ag7k0/kurta/f/j/g/xxl-sg1011-sanganeri-feb-original-imag8w9xbbakjkju.jpeg?q=70',
        brand: 'Riya Creation',
        title: 'Houndstooth Rayon Blend Stitched Anarkali Gown',
        color: 'Blue',
        selling_price: '₹466',
        price: '₹999',
        disscount: '53% off',
        size: '',
    },
    {
        image: 'https://rukminim1.flixcart.com/image/612/612/xif0q/gown/9/5/7/na-s-3-4-sleeve-stitched-sho31krred-saponharsh-na-original-imagmufurbc2znpg.jpeg?q=70',
        brand: 'SAPONHARSH',
        title: 'Printed Viscose Rayon Stitched Anarkali Gown',
        color: 'Red',
        selling_price: '₹449',
        price: '₹1,099',
        disscount: '59% off',
        size: '',
    },
    {
        image: 'https://rukminim1.flixcart.com/image/612/612/kzfvzww0/gown/l/z/g/16-s-short-sleeve-stitched-gown-badami-ne-style-60-original-imagbg8m9dpz4wtw.jpeg?q=70',
        brand: 'NE STYLE',
        title: 'Printed Crepe Stitched Anarkali Gown',
        color: 'Beige',
        selling_price: '₹298',
        price: '₹1,599',
        disscount: '81% off',
        size: '',
    },
    {
        image: 'https://rukminim1.flixcart.com/image/612/612/kzfvzww0/gown/l/z/g/16-s-short-sleeve-stitched-gown-badami-ne-style-60-original-imagbg8m9dpz4wtw.jpeg?q=70',
        brand: 'NE STYLE',
        title: 'Printed Crepe Stitched Anarkali Gown',
        color: 'Beige',
        selling_price: '₹298',
        price: '₹1,599',
        disscount: '81% off',
        size: '',
    },
];
